<a href="https://colab.research.google.com/github/sforceas/machine-learning/blob/master/ML_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

Crear un array con el metodo **np.array([A,B,C])**

In [8]:
a = np.array([10,20,30,40,50,60,70])

Obtener el valor que corresponde a un indice dentro del array. Empieza contando a partir de 0.
**array[indice]**

In [9]:
a[4]

50

Mostrar los datos de un arreglo a partir de una posición.

* A partir del indice (incluido) en adelante: **array[indice :]**
* Desde el inicio hasts al indice (no incluido): **array[: indice]**
* Entre un primer indice (incluido) y un segundo índice (no incluido): **array[indice1 : indice2]**
* A partir del indice (incluido) y saltando intervalos determinados de indices: **array[indice :: intervalo]**

In [16]:
print(a[4:])
print(a[:4])
print(a[2:4])
print(a[0::2])

[50 60 70]
[10 20 30 40]
[30 40]
[10 30 50 70]


Crear un arreglo unidimensional (vector) de ceros o unos con una determinada longitud: 
**np.zeros(longitud)**
**np.ones(longitud)**

In [21]:
print(np.zeros(5))
print(np.ones(10))

[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


Crear un arreglo bidimensional (matriz) de ceros o unos con un determinado numero de columnas y filas: 
**np.zeros((filas,columnas))**
**np.ones((filas,columnas))**

In [23]:
print(np.zeros((2,5)))
print(np.ones((5,2)))

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


Conocer el tipo de variable de un arreglo con type():

ndarray = arreglo de n dimensiones

In [38]:
print(type(np.ones(())))
print(type(3))
print(type(4.3))
print(type('4.3'))

<class 'numpy.ndarray'>
<class 'int'>
<class 'float'>
<class 'str'>


Generar un arreglo de n elementos a partir de un valor inicial y de uno final. La distancia es la misma entre todos los elementos.
**np.linspace(inicial,final,n_elementos)**

In [40]:
b = np.linspace(3,10,5)
print(b)
print(b[2]-b[1])
print(b[4]-b[3])

[ 3.    4.75  6.5   8.25 10.  ]
1.75
1.75


Generar un arreglo de más dimensiones (matriz) con determinados valores. **np.array([[A,B,C],[D,E,F],[G,H,I])**

In [49]:
c = np.array([['A','B','C'],['D','E','F'],['G','H','I']])
print(c)
type(c)

[['A' 'B' 'C']
 ['D' 'E' 'F']
 ['G' 'H' 'I']]


numpy.ndarray

Conocer las dimensiones de un arreglo con **array.ndim**

In [50]:
c.ndim

2

Ordenar los valores de un arreglo con **np.sort(array)**

In [54]:
d = np.array([2,6,3,10,60,1,33,412])
np.sort(d)

array([  1,   2,   3,   6,  10,  33,  60, 412])

Crear una tabla a partir de dos listas de cabecera y datos, asignando nombres a las columnas y tipos de variable.

In [60]:
cabeceras = [('nombre','S10'),('edad',int)]  #S10 string de longitud 10. Int entero
datos = [('Juan',90),('Maria',50),('Javier',23),('Samanta',43)]

usuarios = np.array(datos,dtype=cabeceras)
usuarios

array([(b'Juan', 90), (b'Maria', 50), (b'Javier', 23), (b'Samanta', 43)],
      dtype=[('nombre', 'S10'), ('edad', '<i8')])

Ordenar los datos de un arreglo a partir de una variable.

In [61]:
np.sort(usuarios,order='edad')

array([(b'Javier', 23), (b'Samanta', 43), (b'Maria', 50), (b'Juan', 90)],
      dtype=[('nombre', 'S10'), ('edad', '<i8')])

Generar un array:
* De 0 al limite superior incrementado en 1: **np.arange(lim_sup) 
* De un limite inferior a un limite superior incrementando en 1: **np.arange(lim_inf,lim_sup)**
* De un limite inferior a un limite superior incrementando en intervalos: **np.arange(lim_inf,lim_sup,intervalo)**

In [62]:
print(np.arange(10))
print(np.arange(10,20))
print(np.arange(10,100,5))

[0 1 2 3 4 5 6 7 8 9]
[10 11 12 13 14 15 16 17 18 19]
[10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


Arreglo de n dimensiones (matriz) que esté totalmente contenido con un único valor. **np.full((filas,columnas), valor)**




In [63]:
np.full((3,6),10)

array([[10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10]])

Crear un arreglo de n dimensiones (matriz) que contenga una determinada diagonal. **no.diag([a,b,c,d])**

In [65]:
np.diag([0,3,6,9])

array([[0, 0, 0, 0],
       [0, 3, 0, 0],
       [0, 0, 6, 0],
       [0, 0, 0, 9]])